#!/bin/bash

cat >.env <<EOL
CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
CONTENTFUL_ENV=${CONTENTFUL_ENV}
CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
CRDS_INTERACTIONS_ENDPOINT=${CRDS_INTERACTIONS_ENDPOINT}
EOL