/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LikeButton {
    /**
    * Total number of likes
    */
    'count': number;
    /**
    * Unique identifier for likeable resource
    */
    'id': string;
    /**
    * Boolean indicating whether likeable resource has been liked
    */
    'isLiked': boolean;
    /**
    * Cache key for localStorage
    */
    'key': string;
    /**
    * Label for "like" state
    */
    'likeLabel': string;
    /**
    * Label for "unlike" state
    */
    'unlikeLabel': string;
  }
  interface LikeButtonAttributes extends StencilHTMLAttributes {
    /**
    * Total number of likes
    */
    'count'?: number;
    /**
    * Unique identifier for likeable resource
    */
    'id'?: string;
    /**
    * Boolean indicating whether likeable resource has been liked
    */
    'isLiked'?: boolean;
    /**
    * Cache key for localStorage
    */
    'key'?: string;
    /**
    * Label for "like" state
    */
    'likeLabel'?: string;
    /**
    * Event emitter for "on complete" of like toggle
    */
    'onLikeCompleted'?: (event: CustomEvent) => void;
    /**
    * Label for "unlike" state
    */
    'unlikeLabel'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LikeButton': Components.LikeButton;
  }

  interface StencilIntrinsicElements {
    'like-button': Components.LikeButtonAttributes;
  }


  interface HTMLLikeButtonElement extends Components.LikeButton, HTMLStencilElement {}
  var HTMLLikeButtonElement: {
    prototype: HTMLLikeButtonElement;
    new (): HTMLLikeButtonElement;
  };

  interface HTMLElementTagNameMap {
    'like-button': HTMLLikeButtonElement
  }

  interface ElementTagNameMap {
    'like-button': HTMLLikeButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
